spring:
  application:
    name: sdjpa-intro

  docker:
    compose:
      ## depending which migrate tool you want (liquibase/flyway) you need to overwrite this config and enable liquibase or flyway
      # See intellij runner. currently liquibase is the default
      # file: compose-mysql-with-flyway.yaml
      file: compose-mysql-with-liquibase.yaml
      enabled: true
      stop:
        command: down

  sql:
    init:
      mode: never

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bookuser
    password: password

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/00_changelog-master.xml
    user: bookadmin
    password: password

  flyway:
    enabled: false
    user: bookadmin
    password: password

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

logging:
  level:
    org.zalando.logbook: TRACE
    lorg.hibernate.orm.jdbc.bind: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      - path: /actuator/health/**

server:
  port: 8080
